import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Nav from "./components/Navbar/Nav";
import ResponsiveNav from "./components/Navbar/ResponsiveNav";


const font = Inter({
  weight:["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"],
});

;

export const metadata: Metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${font.className}  antialiased`}
      > <ThemeProvider  attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
       
        <ResponsiveNav/>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
